steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'asia-south1-docker.pkg.dev/${PROJECT_ID}/bird-repo/bird-image', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'asia-south1-docker.pkg.dev/${PROJECT_ID}/bird-repo/bird-image']
