
#steps:
#- name: 'gcr.io/cloud-builders/docker'
#  args: [ 'build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image:tag1', '.' ]
#images:
#- 'us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image:tag1'

steps:
### Add Tag

  - id: 'add-tag'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
          gcloud container images add-tag gcr.io/$PROJECT_ID/quickstart-docker-repo/quickstart-image:tag1 \
            gcr.io/$PROJECT_ID/quickstart-docker-repo/quickstart-image:tag1 \
            --quiet
