steps:
  #Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/clumsy-docker-repo2/clumsy-image:tagteju', '.' ]
images:
- 'us-west2-docker.pkg.dev/$PROJECT_ID/clumsy-docker-repo2/clumsy-image:tagteju'
  #Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/clumsy-docker-repo2/clumsy-image:tagteju', '.' ]
 
